
import os
import sys
import django

# Add backend to path
sys.path.append(os.path.join(os.getcwd(), "backend"))

# Set up Django environment
os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'config.settings')
django.setup()

from chat.models import Conversation, Message
from laravel_modules.ai_brain.central_integration_layer import CentralAI

def test_context_recovery():
    agent = CentralAI()
    agent.initialize()
    
    # Use valid IDs from the database
    valid_org_id = "641b6e01-0d25-4a11-b616-72686a7d15fb"
    valid_user_id = 1
    
    # 1. Create a dummy conversation and messages
    # We simulate a user who just asked "m total sales this year"
    conv = Conversation.objects.create(
        user_id=valid_user_id,
        organization_id=valid_org_id,
        title="Test Context Recovery"
    )
    
    # User message
    Message.objects.create(
        conversation=conv,
        role='user',
        content="m total sales this year"
    )
    
    # Assistant message with intent
    Message.objects.create(
        conversation=conv,
        role='assistant',
        content="Jumla ya mauzo ya mwaka huu ni ...",
        intent="sales" # We simulate that the intent was captured
    )
    
    print(f"Created Test Conversation ID: {conv.id}")
    
    # 2. Now call agent.query with ONLY "chart" but include the conversation_id
    context = {
        "connection_id": "TENANT_001",
        "user_id": 1,
        "conversation_id": conv.id
    }
    
    print("\nQUERY: chart")
    result = agent.query("chart", context)
    
    # Force UTF-8 for emoji support
    if hasattr(sys.stdout, 'buffer'):
        import io
        sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8')
    
    print(f"ANSWER:\n{result.get('answer')}")
    
    if "[CHART_DATA]" in result.get('answer', ''):
        print("\n✅ SUCCESS: Chart data generated by recovering 'sales' intent!")
    else:
        print("\n❌ FAILED: Chart data missing. Context probably not recovered.")

    # Cleanup
    conv.delete()

if __name__ == "__main__":
    print("--- CONTEXT RECOVERY INTEGRATION TEST ---")
    try:
        test_context_recovery()
    except Exception as e:
        print(f"Test Error: {e}")
        import traceback
        traceback.print_exc()
