
import datetime
from typing import Dict, Any

# SOVEREIGN GENERATIVE REPORT ENGINE v1.0
# Automated Business Report Generation (Markdown/Text).

class GenerativeReportEngine:
    def __init__(self):
        self.report_date = datetime.date.today().strftime("%Y-%m-%d")

    def generate_executive_summary(self, data_context: Dict[str, Any]) -> str:
        """
        Creates a high-level summary for CEOs/Directors.
        """
        return (
            f"# EXECUTIVE SUMMARY: {data_context.get('title', 'Untitled Project')}\n"
            f"**Ref ID**: {data_context.get('id', 'N/A')} | **Date**: {self.report_date}\n\n"
            f"## 1. Key Highlights\n"
            f"- **Strategic Goal**: {data_context.get('goal', 'N/A')}\n"
            f"- **Financial Outlook**: {data_context.get('financial_outlook', 'N/A')}\n"
            f"- **Risk Factor**: {data_context.get('risk_level', 'MEDIUM')}\n\n"
            f"## 2. Analysis Overview\n"
            f"{data_context.get('analysis_text', 'No analysis provided.')}\n\n"
            f"## 3. Recommendations\n"
            f"1. {data_context.get('rec_1', 'Review strategy.')}\n"
            f"2. {data_context.get('rec_2', 'Optimize costs.')}\n"
            f"3. {data_context.get('rec_3', 'Monitor market trends.')}\n\n"
            f"--- \n"
            f"*Generated by Sovereign Cortex AI*"
        )

    def generate_feasibility_study(self, project_name: str, costs: float, revenue: float, risks: list) -> str:
        """
        Generates a detailed feasibility report for new ventures.
        """
        roi = ((revenue - costs) / costs) * 100 if costs > 0 else 0
        verdict = "GO" if roi > 20 else "NO GO (Review Required)"
        
        return (
            f"# FEASIBILITY STUDY: {project_name.upper()}\n"
            f"**CONFIDENTIAL** | **AI-Generated Analysis**\n\n"
            f"## 1. Project Financials\n"
            f"- **Estimated Cost**: {costs:,.2f} TZS\n"
            f"- **Projected Revenue**: {revenue:,.2f} TZS\n"
            f"- **Net Profit**: {revenue - costs:,.2f} TZS\n"
            f"- **ROI**: {roi:.2f}%\n\n"
            f"## 2. Risk Assessment\n"
            f"- Primary Risks: {', '.join(risks)}\n"
            f"- Mitigation Strategy: Diversify supply chain and lock in fixed contracts.\n\n"
            f"## 3. AI Verdict\n"
            f"**DECISION: {verdict}**\n"
            f"Reasoning: ROI is {roi:.1f}%, which is {'above' if roi > 20 else 'below'} the 20% threshold."
        )

REPORT_GENERATOR = GenerativeReportEngine()
