# Generated by Django 4.2.27 on 2026-01-23 11:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('partners', '0001_initial'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_id', models.IntegerField(blank=True, null=True)),
                ('type', models.CharField(choices=[('purchase', 'Purchase'), ('sell', 'Sell')], max_length=50)),
                ('status', models.CharField(choices=[('received', 'Received'), ('pending', 'Pending'), ('ordered', 'Ordered'), ('draft', 'Draft'), ('final', 'Final')], max_length=50)),
                ('payment_status', models.CharField(choices=[('paid', 'Paid'), ('due', 'Due'), ('partial', 'Partial')], max_length=50)),
                ('invoice_no', models.CharField(blank=True, max_length=255, null=True)),
                ('ref_no', models.CharField(blank=True, max_length=255, null=True)),
                ('transaction_date', models.DateTimeField()),
                ('total_before_tax', models.DecimalField(decimal_places=4, default=0, max_digits=22)),
                ('tax_amount', models.DecimalField(decimal_places=4, default=0, max_digits=22)),
                ('discount_type', models.CharField(blank=True, max_length=50, null=True)),
                ('discount_amount', models.DecimalField(decimal_places=4, default=0, max_digits=22)),
                ('shipping_details', models.TextField(blank=True, null=True)),
                ('shipping_charges', models.DecimalField(decimal_places=4, default=0, max_digits=22)),
                ('final_total', models.DecimalField(decimal_places=4, default=0, max_digits=22)),
                ('is_direct_sale', models.BooleanField(default=0)),
                ('is_suspend', models.BooleanField(default=0)),
                ('exchange_rate', models.DecimalField(decimal_places=3, default=1, max_digits=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.business')),
                ('commission_agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commission_transactions', to=settings.AUTH_USER_MODEL)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partners.contact')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_transactions', to=settings.AUTH_USER_MODEL)),
                ('tax', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.taxrate')),
            ],
        ),
        migrations.CreateModel(
            name='TransactionSellLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=22)),
                ('unit_price_before_discount', models.DecimalField(decimal_places=4, max_digits=22)),
                ('unit_price', models.DecimalField(decimal_places=4, max_digits=22)),
                ('line_discount_type', models.CharField(blank=True, max_length=50, null=True)),
                ('line_discount_amount', models.DecimalField(decimal_places=4, default=0, max_digits=22)),
                ('item_tax', models.DecimalField(decimal_places=4, default=0, max_digits=22)),
                ('unit_price_inc_tax', models.DecimalField(decimal_places=4, max_digits=22)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.product')),
                ('tax', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.taxrate')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sell_lines', to='sales.transaction')),
                ('variation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.variation')),
            ],
        ),
        migrations.CreateModel(
            name='TransactionPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=4, max_digits=22)),
                ('method', models.CharField(max_length=50)),
                ('payment_ref_no', models.CharField(blank=True, max_length=255, null=True)),
                ('paid_on', models.DateTimeField()),
                ('business', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.business')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='sales.transaction')),
            ],
        ),
    ]
