# Generated by Django 4.2.27 on 2026-01-23 11:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('tax_number_1', models.CharField(blank=True, max_length=100, null=True)),
                ('tax_label_1', models.CharField(blank=True, max_length=10, null=True)),
                ('tax_number_2', models.CharField(blank=True, max_length=100, null=True)),
                ('tax_label_2', models.CharField(blank=True, max_length=10, null=True)),
                ('default_profit_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('accounting_method', models.CharField(choices=[('fifo', 'FIFO'), ('lifo', 'LIFO'), ('avco', 'AVCO')], default='fifo', max_length=10)),
                ('common_settings', models.JSONField(blank=True, default=dict)),
                ('pos_settings', models.JSONField(blank=True, default=dict)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='business_logos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_businesses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100)),
                ('currency', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=25)),
                ('symbol', models.CharField(max_length=25)),
                ('thousand_separator', models.CharField(default=',', max_length=10)),
                ('decimal_separator', models.CharField(default='.', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actual_name', models.CharField(max_length=255)),
                ('short_name', models.CharField(max_length=255)),
                ('allow_decimal', models.BooleanField(default=False)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='core.business')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_units', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TaxRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=4, max_digits=22)),
                ('is_tax_group', models.BooleanField(default=False)),
                ('for_tax_group', models.BooleanField(default=False)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tax_rates', to='core.business')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_taxes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
